sudo: false
language: node_js
node_js:
  - "6"
  - "8"
after_success:
  - "npm run func"
  - "cat artifacts/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
addons:
  sauce_connect:
    username: "roderick.hsiao"
    access_key: "a7c8994f-a04b-4d04-808f-1090f5148079"
